env:
  commonjs: true
  es6: true
  mocha: true
  browser: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  contract: readonly
  artifacts: readonly
  console: readonly
  web3: readonly
  process: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-console: off
}
